package httpf

const (
	AcceptHeader                  = "Accept"
	AcceptCharsetHeader           = "Accept-Charset"
	AcceptEncodingHeader          = "Accept-Encoding"
	AcceptLanguageHeader          = "Accept-Language"
	AcceptRangesHeader            = "Accept-Ranges"
	CacheControlHeader            = "Cache-Control"
	CcHeader                      = "Cc"
	ConnectionHeader              = "Connection"
	ContentIdHeader               = "Content-Id"
	ContentLanguageHeader         = "Content-Language"
	ContentLengthHeader           = "Content-Length"
	ContentTransferEncodingHeader = "Content-Transfer-Encoding"
	ContentTypeHeader             = "Content-Type"
	CookieHeader                  = "Cookie"
	DateHeader                    = "Date"
	ExpiresHeader                 = "Expires"
	FromHeader                    = "From"
	HostHeader                    = "Host"
	LocationHeader                = "Location"
	ServerHeader                  = "Server"
	SetCookieHeader               = "Set-Cookie"
	UserAgentHeader               = "User-Agent"
	XForwardedForHeader           = "X-Forwarded-For"

	ApplicationJsonType        = "application/json"
	ApplicationFormEncodedType = "application/x-www-form-urlencoded"
)
