name: Labeler

on:
  pull_request:
    branches: [ "main" ]

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5.0.0-alpha.1
      with:
        sync-labels: true
